"use client";
import { useCallback, useEffect, useState } from "react";
import { supabase } from "@/lib/supabase/client";
import RFQEditorModal from "@/components/RFQEditorModal";
import AdminPRFullFormModal from "@/components/AdminPRFullFormModal";

type RfqMode = "generation" | "evaluation" | "printing";
const CONFIG: Record<string,{label:string;mode:RfqMode}> = { rfq_generation:{label:"Generate RFQ",mode:"generation"}, rfq_evaluation:{label:"Review RFQ",mode:"evaluation"}, rfq_printing:{label:"Print RFQ",mode:"printing"} };

export default function AdminWorkflowBridge(){
 const [targets,setTargets]=useState<Array<{prNo:string;stage:string}>>([]); const [rfq,setRfq]=useState<{prNo:string;mode:RfqMode}|null>(null); const [pr,setPr]=useState<string|null>(null);
 const refresh=useCallback(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data:p}=await supabase.from("users").select("role,status,is_active").eq("id",user.id).maybeSingle();if(p?.role!=="admin"||p.status!=="approved"||p.is_active!==true)return;const {data}=await supabase.from("purchase_requests").select("pr_no,current_stage").in("current_stage",Object.keys(CONFIG));setTargets((data||[]).map((x:any)=>({prNo:String(x.pr_no||""),stage:String(x.current_stage||"")})).filter(x=>x.prNo&&x.stage));},[]);
 useEffect(()=>{void refresh();const c=supabase.channel("admin-workflow-bridge").on("postgres_changes",{event:"*",schema:"public",table:"purchase_requests"},()=>void refresh()).subscribe();return()=>{void supabase.removeChannel(c)}},[refresh]);
 useEffect(()=>{const mount=()=>{document.querySelectorAll("main table tbody tr").forEach(row=>{const prNo=row.querySelector("td:first-child")?.textContent?.trim()||"";if(!prNo)return;const actions=row.querySelector("td:last-child > div") as HTMLElement|null;if(!actions)return;const key=(s:string)=>Array.from(s).map(ch=>ch.charCodeAt(0).toString(16)).join("");
   if(!actions.querySelector(`[data-full-pr-key="${key(prNo)}"]`)){const b=document.createElement("button");b.type="button";b.dataset.fullPrKey=key(prNo);b.className="admin-workflow-action admin-full-pr-btn";b.title="View complete Purchase Request";b.textContent="Full PR";b.onclick=()=>setPr(prNo);actions.insertBefore(b,actions.firstChild)}
   const target=targets.find(x=>x.prNo===prNo);if(!target)return;const cfg=CONFIG[target.stage];if(!cfg)return;
   const hasRfqButton=Array.from(actions.querySelectorAll("button")).some((node:any)=>/rfq/i.test((node.textContent||"").trim())||/rfq/i.test(node.title||""));
   if(hasRfqButton)return;
   const b=document.createElement("button");b.type="button";b.dataset.rfqWorkflowKey=key(prNo);b.className="admin-workflow-action admin-rfq-workflow-btn";b.title=`${cfg.label} for ${prNo}`;b.textContent=cfg.label;b.onclick=async()=>{if(cfg.mode==="generation"){const r=await fetch("/api/admin/rfq",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({prNo})});const d=await r.json();if(!r.ok){window.alert(d.error||"Unable to prepare RFQ.");return}}setRfq({prNo,mode:cfg.mode})};actions.insertBefore(b,actions.firstChild);
 })};mount();const obs=new MutationObserver(mount);const table=document.querySelector("main table");if(table)obs.observe(table,{childList:true,subtree:true});return()=>{obs.disconnect();document.querySelectorAll("[data-rfq-workflow-key],[data-full-pr-key]").forEach(n=>n.remove())}},[targets]);
 return <><style>{`.admin-workflow-action{display:inline-flex!important;align-items:center;justify-content:center;min-height:34px!important;padding:.48rem .68rem!important;border-radius:.6rem!important;border:1px solid #ddd5ca!important;background:#fff!important;color:#5a1420!important;font-size:10px!important;font-weight:800!important;white-space:nowrap!important;cursor:pointer!important}.admin-workflow-action:hover{border-color:#9a7b2f!important;background:#fff9ec!important;color:#7c1d2e!important}.admin-rfq-workflow-btn{background:linear-gradient(135deg,#7c1d2e,#5a1420)!important;border-color:#7c1d2e!important;color:#fff!important}.admin-rfq-workflow-btn:hover{background:#4d0c0d!important;color:#fff!important}@media(max-width:900px){.admin-workflow-action{font-size:9px!important;padding:.42rem .52rem!important}}@media print{.admin-workflow-action{display:none!important}}`}</style>{rfq&&<RFQEditorModal prNo={rfq.prNo} mode={rfq.mode} onClose={()=>setRfq(null)} onSaved={()=>void refresh()}/>} {pr&&<AdminPRFullFormModal prNo={pr} onClose={()=>setPr(null)}/>}</>;
}
